import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>RighteousTA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/" />
      </Head>

      <header>
      <nav>
        <img />
        <a href='/'>Home</a>
        <a href='/disclosure'>NFA Disclosure</a>
        <a href='/ta'>Technical Analysis</a>
        <a href='/education'>Education</a>
        <a href='/news'>News</a>
        <a href='/donate'>Donate</a>
        <a href='/contact'>Contact</a>
      </nav>
      </header>

      <main className={styles.main}>
        
      </main>
      <footer className={styles.main}>

      </footer>
    </>
  )
}
